EuroApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CodeFirstMembershipSharp;
using EuroApi.Context;
using EuroApi.DAL;
using EuroApi.Models;
using EuroApi.Util;

namespace EuroApi.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IRepository<Match> _matchRepository = new MatchRepository();
        private readonly IRepository<Team> _teamRepository = new TeamRepository();
        private readonly FootyFeudContext _db = new FootyFeudContext();

        public ActionResult Index()
        {
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var matches = _db.KnockoutMatches.Where(x => x.Date > europeanTime).OrderBy(x => x.Date).Take(4).ToList();
            var playedMatches = _db.KnockoutMatches.Where(x => x.HomeTeamGoals != null && x.AwayTeamGoals != null).OrderByDescending(x => x.Date).Take(4).ToList();
            playedMatches.Reverse();
            ViewBag.PlayedMatches = playedMatches;
            var teamsByGroup = new List<List<Team>>();
            
            foreach (var groupId in _teamRepository.GetAll().Select(x => x.Group.Name).Distinct())
            {
                teamsByGroup.Add(_teamRepository.Query(x => x.Group.Name == groupId).ToList());
            }
            var orderedTeams = new List<IEnumerable<Team>>();
            teamsByGroup.ForEach(t => orderedTeams.Add(Standing.SortTeams(t)));
            ViewBag.Groups = orderedTeams;
            ViewBag.Users = GetUserResultList();
            var currentMatch = _db.KnockoutMatches.OrderByDescending(x => x.Date).FirstOrDefault(x => x.Date < europeanTime);
            if (currentMatch != null)
            {
                var todayDate = currentMatch.Date;
                var allCurrent = new List<KnockoutMatch>();
                foreach (var match in _db.KnockoutMatches)
                {
                    if(match.Date == todayDate)
                    {
                        allCurrent.Add(match);
                    }
                }
                var endTime = currentMatch.Date.AddHours(2);
                if(endTime > europeanTime)
                {
                    var matchBets = new List<List<KnockoutMatchResultBet>>();
                    foreach (var match in allCurrent)
                    {
                        matchBets.Add(_db.KnockoutMatchResultBets.Where(x => x.KnockoutMatchId == match.Id).ToList());
                    }
                    ViewBag.CurrentMatchBets = matchBets;
                }
            }
            return View(matches);
        }

        public ActionResult Rules()
        {
            return View();
        }

        private IOrderedEnumerable<User> GetUserResultList()
        {
            var users = _db.Users.ToList();
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var matches = _matchRepository.Query(x => x.Date < europeanTime).ToList();
            foreach (var user in users)
            {
                var usr = user;
                var userBets = _db.MatchResultBets.Where(x => x.User == usr.Username).ToList();
                foreach (var userbet in matches.Select(match => userBets.FirstOrDefault(x => x.MatchId == match.Id)).Where(userbet => userbet != null))
                {
                    user.CorrectOutcomes += userbet.CorrectOutcome();
                    user.CorrectResults += userbet.CorrectBet();
                }
                var knockoutUserBets = _db.KnockoutMatchResultBets.Where(x => x.User == usr.Username).ToList();
                foreach (var knockoutUserBet in knockoutUserBets)
                {
                    user.CorrectOutcomes += knockoutUserBet.CorrectOutcome();
                    user.CorrectResults += knockoutUserBet.CorrectBet();
                }
                user.TournamentBet = new TournamentBet { PlayerBets = new List<PlayerBet>(), TeamBets = new List<TeamBet>() };
                var playerBets = _db.PlayerBets.Where(x => x.User == usr.Username).ToList().DistinctBy(x => x.PlayerBetTypeId);

                foreach (var playerBet in playerBets)
                {
                    user.TournamentBet.PlayerBets.Add(playerBet);
                }
                var teamBets = _db.TeamBets.Where(x => x.User == usr.Username).ToList().DistinctBy(x => x.TeamBetTypeId);
                foreach (var teamBet in teamBets)
                {
                    user.TournamentBet.TeamBets.Add(teamBet);
                }
            }
            return users.OrderByDescending(x => x.Points);
        }
    }

 
}

EuroApi/Controllers/KnockoutMatchResultBetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EuroApi.Context;
using EuroApi.DAL;
using EuroApi.Models;

namespace EuroApi.Controllers
{
    [Authorize]
    public class KnockoutMatchResultBetController : BaseController
    {
        private readonly IRepository<KnockoutMatchResultBet> _repository = new KnockoutMatchResultBetRepository();
        private readonly IRepository<Team> _teamRepository = new TeamRepository();
        private readonly IRepository<KnockoutMatch> _knockoutMatchRepository = new KnockoutMatchRepository();
        private readonly IRepository<MatchResultBet> _matchResultBetRepository = new MatchResultBetRepository();
        private readonly FootyFeudContext _db = new FootyFeudContext();

        public ActionResult Quarter()
        {
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var quarters = _db.KnockoutMatches.Where(x => x.Type == 1 && x.Date > europeanTime).ToList();
            ViewBag.UsersResultBetsKnockout = _db.KnockoutMatchResultBets.Where(x => x.User == User.Identity.Name && x.KnockoutMatch.Type == 1).ToList();
            return View(quarters);
        }

        public ActionResult Semi()
        {
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var quarters = _db.KnockoutMatches.Where(x => x.Type == 2 && x.Date > europeanTime).ToList();
            ViewBag.UsersResultBetsKnockout = _db.KnockoutMatchResultBets.Where(x => x.User == User.Identity.Name && x.KnockoutMatch.Type == 2).ToList();
            return View(quarters);
        }

        public ActionResult Final()
        {
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var quarters = _db.KnockoutMatches.Where(x => x.Type == 3 && x.Date > europeanTime).ToList();
            ViewBag.UsersResultBetsKnockout = _db.KnockoutMatchResultBets.Where(x => x.User == User.Identity.Name && x.KnockoutMatch.Type == 3).ToList();
            return View(quarters);
        }


        public JsonResult SetBet(int? matchId, int? homeGoals, int? awayGoals, int? homeTeamId, int? awayTeamId)
        {
            if (matchId == null || homeGoals == null || awayGoals == null || homeTeamId == null || awayTeamId == null)
                return null;
            var match = _knockoutMatchRepository.Find((int)matchId);
            var europeanTime = DateTime.UtcNow.AddHours(2);
            if (match == null || match.Date < europeanTime) return null;
            var userBet = _repository.Query(x => x.User == User.Identity.Name && x.KnockoutMatchId == matchId && x.KnockoutMatch.Type == match.Type).FirstOrDefault();
            if (userBet == null)
            {
                var userB = new KnockoutMatchResultBet
                {
                    User = User.Identity.Name,
                    KnockoutMatchId = (int)matchId,
                    HomeTeamGoals = (int)homeGoals,
                    AwayTeamGoals = (int)awayGoals,
                    HomeTeamId = (int)homeTeamId,
                    AwayTeamId = (int)awayTeamId,
                };
                _repository.Add(userB);
                _repository.Save();
            }
            else
            {
                userBet.HomeTeamGoals = (int)homeGoals;
                userBet.AwayTeamGoals = (int)awayGoals;
                userBet.HomeTeamId = (int) homeTeamId;
                userBet.AwayTeamId = (int) awayTeamId;
                _repository.Save();
            }
            return Json("Ok");
        }

        private IEnumerable<KnockoutMatch> GetSemiFinalsFromBets()
        {
            var userBets = _repository.Query(x => x.User == User.Identity.Name).ToList();
            var quarterFinals = _knockoutMatchRepository.Query(x => x.Type == KnockoutMatch.QUARTERFINAL).OrderBy(x => x.Date).ToList();
            var semiFinals = _knockoutMatchRepository.Query(x => x.Type == KnockoutMatch.SEMIFINAL).OrderBy(x => x.Date).ToList();
            return UserBetStanding.GetSemiFinals(userBets, quarterFinals, semiFinals);
        }

        private KnockoutMatch GetFinalFromBets()
        {
            var userBets = _repository.Query(x => x.User == User.Identity.Name).ToList();
            var final = _knockoutMatchRepository.Query(x => x.Type == KnockoutMatch.FINAL).FirstOrDefault();
            return UserBetStanding.GetFinal(userBets, final);
        }

        protected string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;
            
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewContext.ViewBag.UsersResultBetsKnockout = _repository.Query(x => x.User == User.Identity.Name).ToList();
                viewResult.View.Render(viewContext, sw);
                return sw.GetStringBuilder().ToString();
            }
        }

        public JsonResult SemiFinals()
        {
            var userBets =
                _repository.Query(x => x.KnockoutMatch.Type == KnockoutMatch.QUARTERFINAL && x.User == User.Identity.Name).
                    ToList();
            var groupBets = _matchResultBetRepository.Query(x => x.User == User.Identity.Name);
            if (userBets.Count >= 4 && groupBets.Count() >= 24)
            {
                var semiFinals = GetSemiFinalsFromBets().ToList();
                if (userBets.Any(x => x.KnockoutMatch.Winner() == null))
                    return Json("Some results are draw in quarter finals.");
                var html = semiFinals.Select(x => RenderPartialViewToString("_UserBetKnockoutMatch", x));
                return Json(html);
            }
            return Json("Set bets in groups and quarter finals before semi finals.");
        }
    }
}

EuroApi/Views/Home/Index.cshtml
@using CodeFirstMembershipSharp
@using EuroApi.Models
@model List<KnockoutMatch>
@{
    ViewBag.Title = "Home";
}
@if (!User.Identity.IsAuthenticated)
{
    <div class="hero-unit span11" style="height: 170px; margin-top: 0px;">
        <h2 style="margin-top: -40px;">FootyFeud</h2>
    
        <section class="features">
        
            <section class="feature">
                <h3>Get an account</h3>
                <a href="/Account/Register"><img src="@Url.Content("~/Content/images/niLYkeG.jpg")" style="box-shadow: 4px 3px 3px #888; height: 150px;" /></a>
            </section>
    
        </section>
    
    </div>
}

<div style="font-size: large">@Html.ActionLink("Bet on final", "Final", "KnockoutMatchResultBet")</div>

@Html.Partial("_Chat")

@{
    var matchesPlayed = (List<KnockoutMatch>)ViewBag.PlayedMatches;
}

<div class="row">
    <div style="" class="span5 well">
        <div class="page-header span6" style="">
            <h2>Upcoming matches</h2>
        </div>
        @foreach (var match in Model)
        {
            <div class="teamsInMatch" style="margin: 1px 0px 10px 0px; font-size: 0.95em;">
                @Html.Partial("_Match", match)
            </div>
        }
        @if (matchesPlayed.Any())
        {
            <div class="page-header span6" style="">
                <h2>Played matches</h2>
            </div>
            foreach (var match in matchesPlayed)
            {
                <div class="teamsInMatch" style="margin: 1px 0px 10px 0px; font-size: 0.95em;">
                    @Html.Partial("_MatchPlayed", match)
                </div>
            }
        }
        
    </div>
        
        
    <div style="display: inline-block;" class="span6 well">
        <div class="page-header span6" style="">
            <h2>Groups</h2>
        </div>

        @foreach (var group in (List<IEnumerable<Team>>)ViewBag.Groups)
        {
            <div class="span3" style="margin: 2px;">
                @Html.Partial("_Group", group)
            </div>
        }
    </div>
</div>

@{
    var currentMatchBetList = ViewBag.CurrentMatchBets == null ? null : (List<List<KnockoutMatchResultBet>>)ViewBag.CurrentMatchBets;    
}
@if (currentMatchBetList != null && currentMatchBetList.Any())
{
    foreach (var currentMatchBets in currentMatchBetList)
    {
        if (!currentMatchBets.Any())
        {
            continue;
        }
        <div style="" class="well">
            <h3>Current match</h3>
            <br />
            @Html.Partial("_MatchHeading", currentMatchBets.First().KnockoutMatch)

            <div class="row" style="font-weight: bold;">
                <div class="span2">
                    User
                </div>
                <div class="span2">
                    Bet
                </div>
            </div>
            @foreach (var currentMatchBet in currentMatchBets)
            {
                <div class="row" style="margin-top: 4px;">
                    <div class="span2">
                        @currentMatchBet.User
                    </div>
                    <div class="span2">
                        @currentMatchBet.HomeTeamGoals - @currentMatchBet.AwayTeamGoals
                    </div>
                </div>
            }
        </div>
    }
} 



@Html.Partial("_Results", (IOrderedEnumerable<User>)ViewBag.Users)
@Html.Partial("_TournamentBets", (IOrderedEnumerable<User>)ViewBag.Users)

EuroApi/Views/Home/_MatchPlayed.cshtml
@model EuroApi.Models.KnockoutMatch

<a href="~/ViewBet/Match/@(Model.Id)">
    <div>
        <div class="teamInMatch"><img src="/Content/flags/@(Model.HomeTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
            @Model.HomeTeam.Name
        </div>
        <div class="teamInMatch"><img src="/Content/flags/@(Model.AwayTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
            @Model.AwayTeam.Name
        </div>
    </div>
    <div>@Model.HomeTeamGoals - @Model.AwayTeamGoals</div>
</a>