EuroApi/Models/TournamentBet.cs
using System.Collections.Generic;

namespace EuroApi.Models
{
    public class TournamentBet
    {
        public List<TeamBet> TeamBets { get; set; }
        public List<PlayerBet> PlayerBets { get; set; }
    }
}

EuroApi/Controllers/ViewBetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EuroApi.Context;
using EuroApi.Models;

namespace EuroApi.Controllers
{
    [Authorize]
    public class ViewBetController : BaseController
    {
        private readonly FootyFeudContext _db = new FootyFeudContext();

        public ActionResult Username(string username)
        {
            var user = _db.Users.FirstOrDefault(x => x.Username == username);
            if (user == null) return null;
            var europeanTime = DateTime.UtcNow.AddHours(2);
            var bets = _db.MatchResultBets.Where(x => x.User == user.Username && x.Match.Date < europeanTime).OrderBy(x => x.Match.Date).ToList();
            ViewBag.KnockoutBets = _db.KnockoutMatchResultBets.Where(x => x.User == user.Username && x.KnockoutMatch.Date < europeanTime).OrderBy(x => x.KnockoutMatch.Date).ToList();
            return View(bets);
        }

        public ActionResult Match(int id)
        {
            var match = _db.KnockoutMatches.Find(id);
            if (match == null) return null;
            var europeanTime = DateTime.UtcNow.AddHours(2);
            if(match.Date < europeanTime)
            {
                var bets = _db.KnockoutMatchResultBets.Where(x => x.KnockoutMatchId == id).ToList();
                return View(bets);
            }
            return View(new List<KnockoutMatchResultBet>());
        }
    }
}

EuroApi/Views/Shared/_Match.cshtml
@model EuroApi.Models.KnockoutMatch

<div>
    <div class="teamInMatch"><img src="/Content/flags/@(Model.HomeTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
        @Model.HomeTeam.Name
    </div>
    <div class="teamInMatch"><img src="/Content/flags/@(Model.AwayTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
        @Model.AwayTeam.Name
    </div>
</div>
    
<div>@Model.Date.ToString("dd.MM.yyyy HH:mm")</div>

EuroApi/Views/Shared/_MatchHeading.cshtml
@model EuroApi.Models.KnockoutMatch

<div class="row well">
        <div class="span2">
            <img src="/Content/flags/@(Model.HomeTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
            @Model.HomeTeam.Name
        </div>
        <div class="span2">
            <img src="/Content/flags/@(Model.AwayTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />                 
            @Model.AwayTeam.Name
        </div>

    </div>

EuroApi/Views/Shared/_Results.cshtml
@model IOrderedEnumerable<CodeFirstMembershipSharp.User>

<div class="page-header span12" style="">
    <h2>Table</h2>
</div>

<div class="row well">
    <div class="row" style="font-weight: bold;">
        <div class="span3">
            User
        </div>
        <div class="span2">
            Points
        </div>
        <div class="span2">
            Correct Outcomes
        </div>
        <div class="span2">
            Correct Results
        </div>
    </div>
    @foreach(var user in Model)
    {
        <div class="row">
            <div class="span3">
                @Html.ActionLink(@user.Username, "Username", "ViewBet", new {username = @user.Username}, null)
            </div>
            <div class="span2">
                @user.Points
            </div>
            <div class="span2">
                @user.CorrectOutcomes
            </div>
            <div class="span2">
                @user.CorrectResults
            </div>
        </div>
    }
</div>

EuroApi/Views/Shared/_TournamentBets.cshtml
@model IOrderedEnumerable<CodeFirstMembershipSharp.User>

<div class="page-header span12" style="">
    <h2>Tournament Bets</h2>
</div>

<div class="row well">
    <div class="row" style="font-weight: bold;">
        <div class="span2">
            User
        </div>
        <div class="span2">
            Top Scorer
        </div>
        <div class="span2">
            Most Assists
        </div>
        <div class="span2">
            Winner
        </div>
        <div class="span2">
            Most Goals
        </div>
        <div class="span2">
            Red Cards
        </div>
    </div>
    @foreach(var user in Model)
    {
        <div class="row">
            <div class="span2">
                @Html.ActionLink(@user.Username, "Username", "ViewBet", new {username = @user.Username}, null)
            </div>
            @foreach(var playerBet in user.TournamentBet.PlayerBets)
            {
                <div class="span2">
                    @playerBet.Player.Name
                </div>
            }
            @foreach(var teamBet in user.TournamentBet.TeamBets)
            {
                <div class="span2">
                    @teamBet.Team.Name
                </div>
            }
        </div>
    }
</div>

EuroApi/Views/Shared/_UserBetKnockoutMatch.cshtml
@using System.Globalization
@using EuroApi.Models
@model KnockoutMatch

@{
    var userBets = (List<KnockoutMatchResultBet>)ViewBag.UsersResultBetsKnockout;
    var userBetHomeResult = "";
    var userBetAwayResult = "";
    var untouched = "untoched";
    var type = "";
    if (Model.Type == KnockoutMatch.QUARTERFINAL)
    {
        type = "quarter";
    } 
    else if(Model.Type == KnockoutMatch.SEMIFINAL)
    {
        type = "semi";
    }
    else if (Model.Type == KnockoutMatch.FINAL)
    {
        type = "final";
    }
    if (userBets != null)
    {
        var userBet = userBets.Where(x => x.KnockoutMatchId == Model.Id).ToList();
        if (userBet.Any())
        {
            userBetHomeResult = userBet.Select(x => x.HomeTeamGoals).FirstOrDefault().ToString(CultureInfo.InvariantCulture);
            userBetAwayResult = userBet.Select(x => x.AwayTeamGoals).FirstOrDefault().ToString(CultureInfo.InvariantCulture);
        }
        untouched = "";
    }
}

<div class="teamsInMatch">
    <div class="teamInMatch"><img src="/Content/flags/@(Model.HomeTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />
        @Model.HomeTeam.Name
    </div>
    <div class="teamInMatch"><img src="/Content/flags/@(Model.AwayTeam.Name)-flag.gif" style='height: 14px;' alt='flag' />                 
        @Model.AwayTeam.Name
    </div>
</div>
<div class="teamsInMatch knockoutBet@(Model.Id)">
    <input class="resultBetKnockout @type homeTeam @untouched" type="tel" homeTeamId="@Model.HomeTeam.Id" awayTeamId="@Model.AwayTeam.Id" matchId="@Model.Id" value="@userBetHomeResult"/>
    <input class="resultBetKnockout @type awayTeam @untouched" type="tel" homeTeamId="@Model.HomeTeam.Id" awayTeamId="@Model.AwayTeam.Id" matchId="@Model.Id" value="@userBetAwayResult" />
    <div class="resultSaved"><img class="resultSavedImage" alt=""/></div>
</div>